buildpack:
  name: Blazar-Buildpack-Java
  branch: js-jdk-toolchains

provides:
  - test_helpers

depends:
  - annotation
  - annotations
  - check_api

env:
  SET_VERSION_OVERRIDE: "2.31.0-$GIT_BRANCH-SNAPSHOT"

