provides:
  - check_api

depends:
  - annotation
  - annotations

env:
  SET_VERSION_OVERRIDE: "2.4.1-$GIT_BRANCH-SNAPSHOT"

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2
