buildpack:
  name: Blazar-Buildpack-Java

provides:
  - core

depends:
  - annotation
  - annotations
  - check_api
  - test_helpers
  - type_annotations

env:
  SET_VERSION_OVERRIDE: "2.27.0-$GIT_BRANCH-SNAPSHOT"
  MAVEN_OPTS: -Xmx2048m

buildResources:
  cpus: 4
  memoryMb: 4096

