provides:
  - docgen_processor

depends:
  - annotation

env:
  SET_VERSION_OVERRIDE: "2.5.1-$GIT_BRANCH-SNAPSHOT"

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2
